workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app-store
        bundle_identifier: com.echodate.me.echodate
        automatic_code_signing: true

    scripts:
      
      - name: Set version number
        script: |
          BUILD_NUMBER=${BUILD_NUMBER:-$(date +%s)}
          flutter pub get
          sed -i '' "s/^version:.*/version: 0.1.1+${BUILD_NUMBER}/" pubspec.yaml

      - name: Initialize keychain
        script: keychain initialize

      - name: Add certificates
        script: keychain add-certificates

      - name: Use provisioning profiles
        script: xcode-project use-profiles

      - name: Get Flutter packages
        script: flutter pub get

      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - timmychris09@gmail.com
