import 'package:get/get.dart';

class PickHobbiesController extends GetxController {
  RxList<Map<String, String>> interests = [
    {"emoji": "⚽", "label": "Football"},
    {"emoji": "🌿", "label": "Nature"},
    {"emoji": "🗣️", "label": "Language"},
    {"emoji": "📸", "label": "Photography"},
    {"emoji": "🌱", "label": "Tech"},
    {"emoji": "🎤", "label": "Singing"},
    {"emoji": "🎾", "label": "Tennis"},
    {"emoji": "✍️", "label": "Writing"},
    {"emoji": "🎭", "label": "Clubbing"},
    {"emoji": "💃", "label": "Dancing"},
    {"emoji": "☕", "label": "Coffee"},
    {"emoji": "💉", "label": "Tattoos"},
    {"emoji": "🎣", "label": "Fishing"},
    {"emoji": "👗", "label": "Fashion"},
    {"emoji": "🏕️", "label": "Camping"},
    {"emoji": "🍳", "label": "Cooking"},
    {"emoji": "🍷", "label": "Wine"},
    {"emoji": "🧘", "label": "Meditation"},
    {"emoji": "🏃", "label": "Running"},
    {"emoji": "🚴", "label": "Cycling"},
    {"emoji": "🧗", "label": "Climbing"},
    {"emoji": "🎮", "label": "Gaming"},
    {"emoji": "📚", "label": "Reading"},
    {"emoji": "🎨", "label": "Painting"},
    {"emoji": "🎬", "label": "Movies"},
    {"emoji": "🎵", "label": "Music"},
    {"emoji": "✈️", "label": "Travel"},
    {"emoji": "🧶", "label": "Knitting"},
    {"emoji": "🎭", "label": "Theater"},
    {"emoji": "🏊", "label": "Swimming"},
    {"emoji": "🍕", "label": "Foodie"},
    {"emoji": "🧁", "label": "Baking"},
    {"emoji": "🚲", "label": "Biking"},
    {"emoji": "🦮", "label": "Dog Walking"},
    {"emoji": "🎯", "label": "Darts"},
    {"emoji": "🎱", "label": "Billiards"},
    {"emoji": "🎺", "label": "Jazz"},
    {"emoji": "🎷", "label": "Saxophone"},
    {"emoji": "🏺", "label": "Pottery"},
    {"emoji": "⛰️", "label": "Hiking"},
    {"emoji": "🌌", "label": "Astronomy"},
    {"emoji": "🎪", "label": "Circus Arts"},
    {"emoji": "🏋️", "label": "Weightlifting"},
    {"emoji": "🧩", "label": "Puzzles"},
    {"emoji": "🏄", "label": "Surfing"},
    {"emoji": "⛷️", "label": "Skiing"},
    {"emoji": "🎲", "label": "Board Games"},
    {"emoji": "🎹", "label": "Piano"},
    {"emoji": "🎸", "label": "Guitar"},
    {"emoji": "🌱", "label": "Gardening"},
    {"emoji": "💻", "label": "Programming"},
    {"emoji": "📝", "label": "Journaling"},
    {"emoji": "🧪", "label": "Science"},
    {"emoji": "🧚", "label": "Cosplay"},
    {"emoji": "🏛️", "label": "Architecture"},
    {"emoji": "🍺", "label": "Craft Beer"},
    {"emoji": "⚒️", "label": "DIY"},
    {"emoji": "🧵", "label": "Sewing"},
    {"emoji": "🔭", "label": "Stargazing"},
    {"emoji": "🎯", "label": "Archery"},
    {"emoji": "🏎️", "label": "Racing"},
    {"emoji": "🦅", "label": "Birdwatching"},
    {"emoji": "🎣", "label": "Angling"},
    {"emoji": "🛹", "label": "Skateboarding"},
    {"emoji": "🎪", "label": "Juggling"},
    {"emoji": "🎭", "label": "Improv"},
    {"emoji": "🎧", "label": "DJing"},
    {"emoji": "📰", "label": "Journalism"},
    {"emoji": "🔮", "label": "Astrology"},
    {"emoji": "🧘‍♂️", "label": "Yoga"},
    {"emoji": "🗡️", "label": "Fencing"},
    {"emoji": "🎻", "label": "Violin"},
    {"emoji": "🎭", "label": "Comedy"},
    {"emoji": "🏹", "label": "Bowman"},
    {"emoji": "🎒", "label": "Backpacking"},
    {"emoji": "🎁", "label": "Crafting"},
    {"emoji": "🥊", "label": "Boxing"},
    {"emoji": "🥋", "label": "Martial Arts"},
    {"emoji": "💰", "label": "Investing"},
    {"emoji": "🕰️", "label": "Antiques"},
    {"emoji": "🐶", "label": "Pet Training"},
    {"emoji": "🛥️", "label": "Boating"},
    {"emoji": "🧲", "label": "Magnet Fishing"},
    {"emoji": "🪞", "label": "Interior Design"},
  ].obs;
  RxList<String> selectedInterests = <String>[].obs;

  void toggleSelection(String interest) {
    if (selectedInterests.contains(interest)) {
      selectedInterests.remove(interest);
    } else {
      selectedInterests.add(interest);
    }
  }
}
